#############################################################################
# Makefile for building: tavli
# Generated by qmake (2.01a) (Qt 4.3.0) on: Sun Jun 24 10:29:26 2007
# Project:  tavli.pro
# Template: app
# Command: /home/alex/t/qt-x11-opensource-src-4.3.0/bin/qmake -unix -o Makefile tavli.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -O3 -funroll-loops -march=pentium4 -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../mkspecs/linux-g++ -I. -I../../../include/QtCore -I../../../include/QtCore -I../../../include/QtNetwork -I../../../include/QtNetwork -I../../../include/QtGui -I../../../include/QtGui -I../../../include -I. -I.moc/release-shared -I.uic/release-shared
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.3.0/lib -Wl,-rpath,/usr/local/Trolltech/Qt-4.3.0/lib
LIBS          = $(SUBLIBS)  -L/home/alex/t/qt-x11-opensource-src-4.3.0/lib -lQtGui -L/home/alex/t/qt-x11-opensource-src-4.3.0/lib -L/usr/X11R6/lib -lpng -lSM -lICE -pthread -L/lib -pthread -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/alex/t/qt-x11-opensource-src-4.3.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = .obj/release-shared/

####### Files

SOURCES       = board.cpp \
		main.cpp \
		mainwindow.cpp \
		player.cpp \
		settings.cpp .moc/release-shared/moc_board.cpp \
		.moc/release-shared/moc_mainwindow.cpp \
		.moc/release-shared/moc_settings.cpp \
		.rcc/release-shared/qrc_tavli.cpp
OBJECTS       = .obj/release-shared/board.o \
		.obj/release-shared/main.o \
		.obj/release-shared/mainwindow.o \
		.obj/release-shared/player.o \
		.obj/release-shared/settings.o \
		.obj/release-shared/moc_board.o \
		.obj/release-shared/moc_mainwindow.o \
		.obj/release-shared/moc_settings.o \
		.obj/release-shared/qrc_tavli.o
DIST          = ../../../mkspecs/common/g++.conf \
		../../../mkspecs/common/unix.conf \
		../../../mkspecs/common/linux.conf \
		../../../mkspecs/features/exclusive_builds.prf \
		../../../mkspecs/features/default_pre.prf \
		../../../.qmake.cache \
		../../../mkspecs/qconfig.pri \
		../../../mkspecs/features/qt_functions.prf \
		../../../mkspecs/features/qt_config.prf \
		../../../mkspecs/features/release.prf \
		../../../mkspecs/features/default_post.prf \
		../../../mkspecs/features/unix/dylib.prf \
		../../../mkspecs/features/unix/separate_debug_info.prf \
		../../../mkspecs/features/unix/largefile.prf \
		../../../mkspecs/features/dll.prf \
		../../../mkspecs/features/shared.prf \
		../../../mkspecs/features/warn_on.prf \
		../../../mkspecs/features/qt.prf \
		../../../mkspecs/features/unix/thread.prf \
		../../../mkspecs/features/moc.prf \
		../../../mkspecs/features/resources.prf \
		../../../mkspecs/features/uic.prf \
		../../../mkspecs/features/yacc.prf \
		../../../mkspecs/features/lex.prf \
		tavli.pro
QMAKE_TARGET  = tavli
DESTDIR       = 
TARGET        = tavli

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): .uic/release-shared/ui_settings.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	(test -z "$(DESTDIR)" || cd "$(DESTDIR)" ; targ=`basename $(TARGET)`; objcopy --only-keep-debug "$$targ" "$$targ.debug" && objcopy --strip-debug "$$targ" && objcopy --add-gnu-debuglink="$$targ.debug" "$$targ" && chmod -x "$$targ.debug" ) ;

Makefile: tavli.pro ../../../.qmake.cache ../../../mkspecs/linux-g++/qmake.conf ../../../mkspecs/common/g++.conf \
		../../../mkspecs/common/unix.conf \
		../../../mkspecs/common/linux.conf \
		../../../mkspecs/features/exclusive_builds.prf \
		../../../mkspecs/features/default_pre.prf \
		../../../.qmake.cache \
		../../../mkspecs/qconfig.pri \
		../../../mkspecs/features/qt_functions.prf \
		../../../mkspecs/features/qt_config.prf \
		../../../mkspecs/features/release.prf \
		../../../mkspecs/features/default_post.prf \
		../../../mkspecs/features/unix/dylib.prf \
		../../../mkspecs/features/unix/separate_debug_info.prf \
		../../../mkspecs/features/unix/largefile.prf \
		../../../mkspecs/features/dll.prf \
		../../../mkspecs/features/shared.prf \
		../../../mkspecs/features/warn_on.prf \
		../../../mkspecs/features/qt.prf \
		../../../mkspecs/features/unix/thread.prf \
		../../../mkspecs/features/moc.prf \
		../../../mkspecs/features/resources.prf \
		../../../mkspecs/features/uic.prf \
		../../../mkspecs/features/yacc.prf \
		../../../mkspecs/features/lex.prf \
		/home/alex/t/qt-x11-opensource-src-4.3.0/lib/libQtGui.prl \
		/home/alex/t/qt-x11-opensource-src-4.3.0/lib/libQtCore.prl \
		/home/alex/t/qt-x11-opensource-src-4.3.0/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile tavli.pro
../../../mkspecs/common/g++.conf:
../../../mkspecs/common/unix.conf:
../../../mkspecs/common/linux.conf:
../../../mkspecs/features/exclusive_builds.prf:
../../../mkspecs/features/default_pre.prf:
../../../.qmake.cache:
../../../mkspecs/qconfig.pri:
../../../mkspecs/features/qt_functions.prf:
../../../mkspecs/features/qt_config.prf:
../../../mkspecs/features/release.prf:
../../../mkspecs/features/default_post.prf:
../../../mkspecs/features/unix/dylib.prf:
../../../mkspecs/features/unix/separate_debug_info.prf:
../../../mkspecs/features/unix/largefile.prf:
../../../mkspecs/features/dll.prf:
../../../mkspecs/features/shared.prf:
../../../mkspecs/features/warn_on.prf:
../../../mkspecs/features/qt.prf:
../../../mkspecs/features/unix/thread.prf:
../../../mkspecs/features/moc.prf:
../../../mkspecs/features/resources.prf:
../../../mkspecs/features/uic.prf:
../../../mkspecs/features/yacc.prf:
../../../mkspecs/features/lex.prf:
/home/alex/t/qt-x11-opensource-src-4.3.0/lib/libQtGui.prl:
/home/alex/t/qt-x11-opensource-src-4.3.0/lib/libQtCore.prl:
/home/alex/t/qt-x11-opensource-src-4.3.0/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile tavli.pro

dist: 
	@$(CHK_DIR_EXISTS) .obj/release-shared/tavli1.0.0 || $(MKDIR) .obj/release-shared/tavli1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .obj/release-shared/tavli1.0.0/ && $(COPY_FILE) --parents board.h mainwindow.h player.h settings.h .obj/release-shared/tavli1.0.0/ && $(COPY_FILE) --parents tavli.qrc .obj/release-shared/tavli1.0.0/ && $(COPY_FILE) --parents board.cpp main.cpp mainwindow.cpp player.cpp settings.cpp .obj/release-shared/tavli1.0.0/ && $(COPY_FILE) --parents settings.ui .obj/release-shared/tavli1.0.0/ && $(COPY_FILE) --parents tavli_el.ts .obj/release-shared/tavli1.0.0/ && (cd `dirname .obj/release-shared/tavli1.0.0` && $(TAR) tavli1.0.0.tar tavli1.0.0 && $(COMPRESS) tavli1.0.0.tar) && $(MOVE) `dirname .obj/release-shared/tavli1.0.0`/tavli1.0.0.tar.gz . && $(DEL_FILE) -r .obj/release-shared/tavli1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) `basename $(TARGET)`.debug
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: .moc/release-shared/moc_board.cpp .moc/release-shared/moc_mainwindow.cpp .moc/release-shared/moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/release-shared/moc_board.cpp .moc/release-shared/moc_mainwindow.cpp .moc/release-shared/moc_settings.cpp
.moc/release-shared/moc_board.cpp: ../../../include/QtGui/QWidget \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/QPoint \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		../../../include/QtGui/QImage \
		../../../include/QtGui/QPixmap \
		board.h
	/home/alex/t/qt-x11-opensource-src-4.3.0/bin/moc $(DEFINES) $(INCPATH) board.h -o .moc/release-shared/moc_board.cpp

.moc/release-shared/moc_mainwindow.cpp: ../../../include/QtGui/QMainWindow \
		../../../include/QtGui/qmainwindow.h \
		../../../src/gui/widgets/qmainwindow.h \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/QPoint \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		mainwindow.h
	/home/alex/t/qt-x11-opensource-src-4.3.0/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o .moc/release-shared/moc_mainwindow.cpp

.moc/release-shared/moc_settings.cpp: .uic/release-shared/ui_settings.h \
		../../../include/QtCore/QVariant \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtGui/QAction \
		../../../include/QtGui/qaction.h \
		../../../src/gui/kernel/qaction.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/QPoint \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		../../../include/QtGui/qicon.h \
		../../../src/gui/image/qicon.h \
		../../../include/QtGui/qactiongroup.h \
		../../../src/gui/kernel/qactiongroup.h \
		../../../include/QtGui/QApplication \
		../../../include/QtGui/qapplication.h \
		../../../src/gui/kernel/qapplication.h \
		../../../include/QtCore/qcoreapplication.h \
		../../../src/corelib/kernel/qcoreapplication.h \
		../../../include/QtCore/qeventloop.h \
		../../../src/corelib/kernel/qeventloop.h \
		../../../include/QtGui/qdesktopwidget.h \
		../../../src/gui/kernel/qdesktopwidget.h \
		../../../include/QtGui/QButtonGroup \
		../../../include/QtGui/qbuttongroup.h \
		../../../src/gui/widgets/qbuttongroup.h \
		../../../include/QtGui/QCheckBox \
		../../../include/QtGui/qcheckbox.h \
		../../../src/gui/widgets/qcheckbox.h \
		../../../include/QtGui/qabstractbutton.h \
		../../../src/gui/widgets/qabstractbutton.h \
		../../../include/QtGui/QDialog \
		../../../include/QtGui/qdialog.h \
		../../../src/gui/dialogs/qdialog.h \
		../../../include/QtGui/QGroupBox \
		../../../include/QtGui/qgroupbox.h \
		../../../src/gui/widgets/qgroupbox.h \
		../../../include/QtGui/qframe.h \
		../../../src/gui/widgets/qframe.h \
		../../../include/QtGui/QHBoxLayout \
		../../../include/QtGui/qboxlayout.h \
		../../../src/gui/kernel/qboxlayout.h \
		../../../include/QtGui/qlayout.h \
		../../../src/gui/kernel/qlayout.h \
		../../../include/QtGui/qlayoutitem.h \
		../../../src/gui/kernel/qlayoutitem.h \
		../../../include/QtGui/qgridlayout.h \
		../../../src/gui/kernel/qgridlayout.h \
		../../../include/QtGui/QLabel \
		../../../include/QtGui/qlabel.h \
		../../../src/gui/widgets/qlabel.h \
		../../../include/QtGui/QLineEdit \
		../../../include/QtGui/qlineedit.h \
		../../../src/gui/widgets/qlineedit.h \
		../../../include/QtGui/QPushButton \
		../../../include/QtGui/qpushbutton.h \
		../../../src/gui/widgets/qpushbutton.h \
		../../../include/QtGui/QRadioButton \
		../../../include/QtGui/qradiobutton.h \
		../../../src/gui/widgets/qradiobutton.h \
		../../../include/QtGui/QSpacerItem \
		../../../include/QtGui/QSpinBox \
		../../../include/QtGui/qspinbox.h \
		../../../src/gui/widgets/qspinbox.h \
		../../../include/QtGui/qabstractspinbox.h \
		../../../src/gui/widgets/qabstractspinbox.h \
		../../../include/QtGui/qvalidator.h \
		../../../src/gui/widgets/qvalidator.h \
		../../../include/QtCore/qlocale.h \
		../../../src/corelib/tools/qlocale.h \
		../../../include/QtGui/QVBoxLayout \
		settings.h
	/home/alex/t/qt-x11-opensource-src-4.3.0/bin/moc $(DEFINES) $(INCPATH) settings.h -o .moc/release-shared/moc_settings.cpp

compiler_rcc_make_all: .rcc/release-shared/qrc_tavli.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/release-shared/qrc_tavli.cpp
.rcc/release-shared/qrc_tavli.cpp: tavli.qrc \
		images/tavli.png \
		images/open.png \
		images/3.png \
		images/redo.png \
		images/kontact_contacts.png \
		images/red_pawn.png \
		images/server.png \
		images/4.png \
		images/white_pawn.png \
		images/paste.png \
		images/save.png \
		images/board.png \
		images/5.png \
		images/1.png \
		images/undo.png \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/roll.png \
		images/6.png \
		images/network.png \
		images/2.png
	/home/alex/t/qt-x11-opensource-src-4.3.0/bin/rcc -name tavli tavli.qrc -o .rcc/release-shared/qrc_tavli.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: .uic/release-shared/ui_settings.h
compiler_uic_clean:
	-$(DEL_FILE) .uic/release-shared/ui_settings.h
.uic/release-shared/ui_settings.h: settings.ui
	/home/alex/t/qt-x11-opensource-src-4.3.0/bin/uic settings.ui -o .uic/release-shared/ui_settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

.obj/release-shared/board.o: board.cpp board.h \
		../../../include/QtGui/QWidget \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/QPoint \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		../../../include/QtGui/QImage \
		../../../include/QtGui/QPixmap \
		../../../include/QtGui/QPainter \
		../../../include/QtGui/qpainter.h \
		../../../src/gui/painting/qpainter.h \
		../../../include/QtGui/qtextoption.h \
		../../../src/gui/text/qtextoption.h \
		../../../include/QtGui/qdrawutil.h \
		../../../src/gui/painting/qdrawutil.h \
		../../../include/QtGui/qpen.h \
		../../../src/gui/painting/qpen.h \
		../../../include/QtGui/QCursor \
		../../../include/QtCore/QDateTime \
		../../../include/QtCore/qdatetime.h \
		../../../src/corelib/tools/qdatetime.h \
		../../../include/QtGui/QMouseEvent
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/board.o board.cpp

.obj/release-shared/main.o: main.cpp ../../../include/QtGui/QApplication \
		../../../include/QtGui/qapplication.h \
		../../../src/gui/kernel/qapplication.h \
		../../../include/QtCore/qcoreapplication.h \
		../../../src/corelib/kernel/qcoreapplication.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtCore/qeventloop.h \
		../../../src/corelib/kernel/qeventloop.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qdesktopwidget.h \
		../../../src/gui/kernel/qdesktopwidget.h \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/QPoint \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		../../../include/QtCore/QLocale \
		../../../include/QtCore/qlocale.h \
		../../../src/corelib/tools/qlocale.h \
		../../../include/QtCore/QTranslator \
		../../../include/QtCore/qtranslator.h \
		../../../src/corelib/kernel/qtranslator.h \
		mainwindow.h \
		../../../include/QtGui/QMainWindow \
		../../../include/QtGui/qmainwindow.h \
		../../../src/gui/widgets/qmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/main.o main.cpp

.obj/release-shared/mainwindow.o: mainwindow.cpp ../../../include/QtGui/QtGui \
		../../../include/QtCore/QtCore \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtCore/qdebug.h \
		../../../src/corelib/io/qdebug.h \
		../../../include/QtCore/qhash.h \
		../../../src/corelib/tools/qhash.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtCore/qtextstream.h \
		../../../src/corelib/io/qtextstream.h \
		../../../include/QtCore/qtextcodec.h \
		../../../src/corelib/codecs/qtextcodec.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtCore/QPoint \
		../../../include/QtCore/qset.h \
		../../../src/corelib/tools/qset.h \
		../../../include/QtCore/qtemporaryfile.h \
		../../../src/corelib/io/qtemporaryfile.h \
		../../../include/QtCore/qfile.h \
		../../../src/corelib/io/qfile.h \
		../../../include/QtCore/qfsfileengine.h \
		../../../src/corelib/io/qfsfileengine.h \
		../../../include/QtCore/qabstractfileengine.h \
		../../../src/corelib/io/qabstractfileengine.h \
		../../../include/QtCore/qdir.h \
		../../../src/corelib/io/qdir.h \
		../../../include/QtCore/qfileinfo.h \
		../../../src/corelib/io/qfileinfo.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtCore/qprocess.h \
		../../../src/corelib/io/qprocess.h \
		../../../include/QtCore/qresource.h \
		../../../src/corelib/io/qresource.h \
		../../../include/QtCore/qlocale.h \
		../../../src/corelib/tools/qlocale.h \
		../../../include/QtCore/qdiriterator.h \
		../../../src/corelib/io/qdiriterator.h \
		../../../include/QtCore/qbuffer.h \
		../../../src/corelib/io/qbuffer.h \
		../../../include/QtCore/qfilesystemwatcher.h \
		../../../src/corelib/io/qfilesystemwatcher.h \
		../../../include/QtCore/qurl.h \
		../../../src/corelib/io/qurl.h \
		../../../include/QtCore/qsettings.h \
		../../../src/corelib/io/qsettings.h \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qcache.h \
		../../../src/corelib/tools/qcache.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtCore/qbitarray.h \
		../../../src/corelib/tools/qbitarray.h \
		../../../include/QtCore/qbytearraymatcher.h \
		../../../src/corelib/tools/qbytearraymatcher.h \
		../../../include/QtCore/qqueue.h \
		../../../src/corelib/tools/qqueue.h \
		../../../include/QtCore/qvarlengtharray.h \
		../../../src/corelib/tools/qvarlengtharray.h \
		../../../include/QtCore/qcontainerfwd.h \
		../../../src/corelib/tools/qcontainerfwd.h \
		../../../include/QtCore/qshareddata.h \
		../../../src/corelib/tools/qshareddata.h \
		../../../include/QtCore/qcryptographichash.h \
		../../../src/corelib/tools/qcryptographichash.h \
		../../../include/QtCore/qstack.h \
		../../../src/corelib/tools/qstack.h \
		../../../include/QtCore/qdatetime.h \
		../../../src/corelib/tools/qdatetime.h \
		../../../include/QtCore/qtimeline.h \
		../../../src/corelib/tools/qtimeline.h \
		../../../include/QtCore/qtextcodecplugin.h \
		../../../src/corelib/codecs/qtextcodecplugin.h \
		../../../include/QtCore/qplugin.h \
		../../../src/corelib/plugin/qplugin.h \
		../../../include/QtCore/qpointer.h \
		../../../src/corelib/kernel/qpointer.h \
		../../../include/QtCore/qfactoryinterface.h \
		../../../src/corelib/plugin/qfactoryinterface.h \
		../../../include/QtCore/qlibraryinfo.h \
		../../../src/corelib/global/qlibraryinfo.h \
		../../../include/QtCore/qendian.h \
		../../../src/corelib/global/qendian.h \
		../../../include/QtCore/qnumeric.h \
		../../../src/corelib/global/qnumeric.h \
		../../../include/QtCore/qtranslator.h \
		../../../src/corelib/kernel/qtranslator.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtCore/qeventloop.h \
		../../../src/corelib/kernel/qeventloop.h \
		../../../include/QtCore/qcoreapplication.h \
		../../../src/corelib/kernel/qcoreapplication.h \
		../../../include/QtCore/qabstractitemmodel.h \
		../../../src/corelib/kernel/qabstractitemmodel.h \
		../../../include/QtCore/qsignalmapper.h \
		../../../src/corelib/kernel/qsignalmapper.h \
		../../../include/QtCore/qobjectcleanuphandler.h \
		../../../src/corelib/kernel/qobjectcleanuphandler.h \
		../../../include/QtCore/qbasictimer.h \
		../../../src/corelib/kernel/qbasictimer.h \
		../../../include/QtCore/qsocketnotifier.h \
		../../../src/corelib/kernel/qsocketnotifier.h \
		../../../include/QtCore/qtimer.h \
		../../../src/corelib/kernel/qtimer.h \
		../../../include/QtCore/qabstracteventdispatcher.h \
		../../../src/corelib/kernel/qabstracteventdispatcher.h \
		../../../include/QtCore/qmetaobject.h \
		../../../src/corelib/kernel/qmetaobject.h \
		../../../include/QtCore/qpluginloader.h \
		../../../src/corelib/plugin/qpluginloader.h \
		../../../include/QtCore/quuid.h \
		../../../src/corelib/plugin/quuid.h \
		../../../include/QtCore/qlibrary.h \
		../../../src/corelib/plugin/qlibrary.h \
		../../../include/QtCore/qsemaphore.h \
		../../../src/corelib/thread/qsemaphore.h \
		../../../include/QtCore/qthreadstorage.h \
		../../../src/corelib/thread/qthreadstorage.h \
		../../../include/QtCore/qwaitcondition.h \
		../../../src/corelib/thread/qwaitcondition.h \
		../../../include/QtCore/qthread.h \
		../../../src/corelib/thread/qthread.h \
		../../../include/QtCore/qmutex.h \
		../../../src/corelib/thread/qmutex.h \
		../../../include/QtCore/qreadwritelock.h \
		../../../src/corelib/thread/qreadwritelock.h \
		../../../include/QtGui/qtextobject.h \
		../../../src/gui/text/qtextobject.h \
		../../../include/QtGui/qtextformat.h \
		../../../src/gui/text/qtextformat.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtGui/qpen.h \
		../../../src/gui/painting/qpen.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontdatabase.h \
		../../../src/gui/text/qfontdatabase.h \
		../../../include/QtGui/qtextdocument.h \
		../../../src/gui/text/qtextdocument.h \
		../../../include/QtGui/qtextoption.h \
		../../../src/gui/text/qtextoption.h \
		../../../include/QtGui/qtexttable.h \
		../../../src/gui/text/qtexttable.h \
		../../../include/QtGui/qtextlayout.h \
		../../../src/gui/text/qtextlayout.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		../../../include/QtGui/qtextlist.h \
		../../../src/gui/text/qtextlist.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qtextdocumentfragment.h \
		../../../src/gui/text/qtextdocumentfragment.h \
		../../../include/QtGui/qtextcursor.h \
		../../../src/gui/text/qtextcursor.h \
		../../../include/QtGui/qabstracttextdocumentlayout.h \
		../../../src/gui/text/qabstracttextdocumentlayout.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qsyntaxhighlighter.h \
		../../../src/gui/text/qsyntaxhighlighter.h \
		../../../include/QtGui/qundogroup.h \
		../../../src/gui/util/qundogroup.h \
		../../../include/QtGui/qdesktopservices.h \
		../../../src/gui/util/qdesktopservices.h \
		../../../include/QtGui/qundoview.h \
		../../../src/gui/util/qundoview.h \
		../../../include/QtGui/qlistview.h \
		../../../src/gui/itemviews/qlistview.h \
		../../../include/QtGui/qabstractitemview.h \
		../../../src/gui/itemviews/qabstractitemview.h \
		../../../include/QtGui/qabstractscrollarea.h \
		../../../src/gui/widgets/qabstractscrollarea.h \
		../../../include/QtGui/qframe.h \
		../../../src/gui/widgets/qframe.h \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qitemselectionmodel.h \
		../../../src/gui/itemviews/qitemselectionmodel.h \
		../../../include/QtGui/qabstractitemdelegate.h \
		../../../src/gui/itemviews/qabstractitemdelegate.h \
		../../../include/QtGui/qstyleoption.h \
		../../../src/gui/styles/qstyleoption.h \
		../../../include/QtGui/qabstractspinbox.h \
		../../../src/gui/widgets/qabstractspinbox.h \
		../../../include/QtGui/qvalidator.h \
		../../../src/gui/widgets/qvalidator.h \
		../../../include/QtGui/qicon.h \
		../../../src/gui/image/qicon.h \
		../../../include/QtGui/qslider.h \
		../../../src/gui/widgets/qslider.h \
		../../../include/QtGui/qabstractslider.h \
		../../../src/gui/widgets/qabstractslider.h \
		../../../include/QtGui/qstyle.h \
		../../../src/gui/styles/qstyle.h \
		../../../include/QtGui/qtabbar.h \
		../../../src/gui/widgets/qtabbar.h \
		../../../include/QtGui/qtabwidget.h \
		../../../src/gui/widgets/qtabwidget.h \
		../../../include/QtGui/qrubberband.h \
		../../../src/gui/widgets/qrubberband.h \
		../../../include/QtGui/qcompleter.h \
		../../../src/gui/util/qcompleter.h \
		../../../include/QtGui/qundostack.h \
		../../../src/gui/util/qundostack.h \
		../../../include/QtGui/qsystemtrayicon.h \
		../../../src/gui/util/qsystemtrayicon.h \
		../../../include/QtGui/qabstractpagesetupdialog.h \
		../../../src/gui/dialogs/qabstractpagesetupdialog.h \
		../../../include/QtGui/qdialog.h \
		../../../src/gui/dialogs/qdialog.h \
		../../../include/QtGui/qcolordialog.h \
		../../../src/gui/dialogs/qcolordialog.h \
		../../../include/QtGui/qfontdialog.h \
		../../../src/gui/dialogs/qfontdialog.h \
		../../../include/QtGui/qmessagebox.h \
		../../../src/gui/dialogs/qmessagebox.h \
		../../../include/QtGui/qprogressdialog.h \
		../../../src/gui/dialogs/qprogressdialog.h \
		../../../include/QtGui/qerrormessage.h \
		../../../src/gui/dialogs/qerrormessage.h \
		../../../include/QtGui/qfiledialog.h \
		../../../src/gui/dialogs/qfiledialog.h \
		../../../include/QtGui/qprintdialog.h \
		../../../src/gui/dialogs/qprintdialog.h \
		../../../include/QtGui/qabstractprintdialog.h \
		../../../src/gui/dialogs/qabstractprintdialog.h \
		../../../include/QtGui/qwizard.h \
		../../../src/gui/dialogs/qwizard.h \
		../../../include/QtGui/qpagesetupdialog.h \
		../../../src/gui/dialogs/qpagesetupdialog.h \
		../../../include/QtGui/qinputdialog.h \
		../../../src/gui/dialogs/qinputdialog.h \
		../../../include/QtGui/qlineedit.h \
		../../../src/gui/widgets/qlineedit.h \
		../../../include/QtGui/qpixmapcache.h \
		../../../src/gui/image/qpixmapcache.h \
		../../../include/QtGui/qimageiohandler.h \
		../../../src/gui/image/qimageiohandler.h \
		../../../include/QtGui/qpicture.h \
		../../../src/gui/image/qpicture.h \
		../../../include/QtGui/qimagereader.h \
		../../../src/gui/image/qimagereader.h \
		../../../include/QtGui/qimagewriter.h \
		../../../src/gui/image/qimagewriter.h \
		../../../include/QtGui/qmovie.h \
		../../../src/gui/image/qmovie.h \
		../../../include/QtGui/qiconengineplugin.h \
		../../../src/gui/image/qiconengineplugin.h \
		../../../include/QtGui/qiconengine.h \
		../../../src/gui/image/qiconengine.h \
		../../../include/QtGui/qbitmap.h \
		../../../src/gui/image/qbitmap.h \
		../../../include/QtGui/qpictureformatplugin.h \
		../../../src/gui/image/qpictureformatplugin.h \
		../../../include/QtGui/qcolormap.h \
		../../../src/gui/painting/qcolormap.h \
		../../../include/QtGui/qprintengine.h \
		../../../src/gui/painting/qprintengine.h \
		../../../include/QtGui/qprinter.h \
		../../../src/gui/painting/qprinter.h \
		../../../include/QtGui/qstylepainter.h \
		../../../src/gui/painting/qstylepainter.h \
		../../../include/QtGui/qpainter.h \
		../../../src/gui/painting/qpainter.h \
		../../../include/QtGui/qdrawutil.h \
		../../../src/gui/painting/qdrawutil.h \
		../../../include/QtGui/qpaintengine.h \
		../../../src/gui/painting/qpaintengine.h \
		../../../include/QtGui/qtreewidgetitemiterator.h \
		../../../src/gui/itemviews/qtreewidgetitemiterator.h \
		../../../include/QtGui/qdatawidgetmapper.h \
		../../../src/gui/itemviews/qdatawidgetmapper.h \
		../../../include/QtGui/qfileiconprovider.h \
		../../../src/gui/itemviews/qfileiconprovider.h \
		../../../include/QtGui/qstringlistmodel.h \
		../../../src/gui/itemviews/qstringlistmodel.h \
		../../../include/QtGui/qlistwidget.h \
		../../../src/gui/itemviews/qlistwidget.h \
		../../../include/QtGui/qdirmodel.h \
		../../../src/gui/itemviews/qdirmodel.h \
		../../../include/QtGui/qcolumnview.h \
		../../../src/gui/itemviews/qcolumnview.h \
		../../../include/QtGui/qstandarditemmodel.h \
		../../../src/gui/itemviews/qstandarditemmodel.h \
		../../../include/QtGui/qsortfilterproxymodel.h \
		../../../src/gui/itemviews/qsortfilterproxymodel.h \
		../../../include/QtGui/qabstractproxymodel.h \
		../../../src/gui/itemviews/qabstractproxymodel.h \
		../../../include/QtGui/qitemdelegate.h \
		../../../src/gui/itemviews/qitemdelegate.h \
		../../../include/QtGui/qtablewidget.h \
		../../../src/gui/itemviews/qtablewidget.h \
		../../../include/QtGui/qtableview.h \
		../../../src/gui/itemviews/qtableview.h \
		../../../include/QtGui/qtreeview.h \
		../../../src/gui/itemviews/qtreeview.h \
		../../../include/QtGui/qproxymodel.h \
		../../../src/gui/itemviews/qproxymodel.h \
		../../../include/QtGui/qheaderview.h \
		../../../src/gui/itemviews/qheaderview.h \
		../../../include/QtGui/qitemeditorfactory.h \
		../../../src/gui/itemviews/qitemeditorfactory.h \
		../../../include/QtGui/qtreewidget.h \
		../../../src/gui/itemviews/qtreewidget.h \
		../../../include/QtGui/qaccessiblebridge.h \
		../../../src/gui/accessible/qaccessiblebridge.h \
		../../../include/QtGui/qaccessiblewidget.h \
		../../../src/gui/accessible/qaccessiblewidget.h \
		../../../include/QtGui/qaccessibleobject.h \
		../../../src/gui/accessible/qaccessibleobject.h \
		../../../include/QtGui/qaccessible.h \
		../../../src/gui/accessible/qaccessible.h \
		../../../include/QtGui/qaccessible2.h \
		../../../src/gui/accessible/qaccessible2.h \
		../../../include/QtGui/qaccessibleplugin.h \
		../../../src/gui/accessible/qaccessibleplugin.h \
		../../../include/QtGui/qclipboard.h \
		../../../src/gui/kernel/qclipboard.h \
		../../../include/QtGui/qwhatsthis.h \
		../../../src/gui/kernel/qwhatsthis.h \
		../../../include/QtGui/qdesktopwidget.h \
		../../../src/gui/kernel/qdesktopwidget.h \
		../../../include/QtGui/qboxlayout.h \
		../../../src/gui/kernel/qboxlayout.h \
		../../../include/QtGui/qlayout.h \
		../../../src/gui/kernel/qlayout.h \
		../../../include/QtGui/qlayoutitem.h \
		../../../src/gui/kernel/qlayoutitem.h \
		../../../include/QtGui/qgridlayout.h \
		../../../src/gui/kernel/qgridlayout.h \
		../../../include/QtGui/qshortcut.h \
		../../../src/gui/kernel/qshortcut.h \
		../../../include/QtGui/qsessionmanager.h \
		../../../src/gui/kernel/qsessionmanager.h \
		../../../include/QtGui/qapplication.h \
		../../../src/gui/kernel/qapplication.h \
		../../../include/QtGui/qaction.h \
		../../../src/gui/kernel/qaction.h \
		../../../include/QtGui/qactiongroup.h \
		../../../src/gui/kernel/qactiongroup.h \
		../../../include/QtGui/qsound.h \
		../../../src/gui/kernel/qsound.h \
		../../../include/QtGui/qstackedlayout.h \
		../../../src/gui/kernel/qstackedlayout.h \
		../../../include/QtGui/qwidgetaction.h \
		../../../src/gui/kernel/qwidgetaction.h \
		../../../include/QtGui/qtooltip.h \
		../../../src/gui/kernel/qtooltip.h \
		../../../include/QtGui/qmotifstyle.h \
		../../../src/gui/styles/qmotifstyle.h \
		../../../include/QtGui/qcommonstyle.h \
		../../../src/gui/styles/qcommonstyle.h \
		../../../include/QtGui/qcleanlooksstyle.h \
		../../../src/gui/styles/qcleanlooksstyle.h \
		../../../include/QtGui/qwindowsstyle.h \
		../../../src/gui/styles/qwindowsstyle.h \
		../../../include/QtGui/qstyleplugin.h \
		../../../src/gui/styles/qstyleplugin.h \
		../../../include/QtGui/qwindowsxpstyle.h \
		../../../src/gui/styles/qwindowsxpstyle.h \
		../../../include/QtGui/qcdestyle.h \
		../../../src/gui/styles/qcdestyle.h \
		../../../include/QtGui/qplastiquestyle.h \
		../../../src/gui/styles/qplastiquestyle.h \
		../../../include/QtGui/qwindowsvistastyle.h \
		../../../src/gui/styles/qwindowsvistastyle.h \
		../../../include/QtGui/qstylefactory.h \
		../../../src/gui/styles/qstylefactory.h \
		../../../include/QtGui/qinputcontextplugin.h \
		../../../src/gui/inputmethod/qinputcontextplugin.h \
		../../../include/QtGui/qinputcontextfactory.h \
		../../../src/gui/inputmethod/qinputcontextfactory.h \
		../../../include/QtGui/qinputcontext.h \
		../../../src/gui/inputmethod/qinputcontext.h \
		../../../include/QtGui/qgraphicsitem.h \
		../../../src/gui/graphicsview/qgraphicsitem.h \
		../../../include/QtGui/qgraphicsscene.h \
		../../../src/gui/graphicsview/qgraphicsscene.h \
		../../../include/QtGui/qgraphicsview.h \
		../../../src/gui/graphicsview/qgraphicsview.h \
		../../../include/QtGui/qscrollarea.h \
		../../../src/gui/widgets/qscrollarea.h \
		../../../include/QtGui/qgraphicssceneevent.h \
		../../../src/gui/graphicsview/qgraphicssceneevent.h \
		../../../include/QtGui/qgraphicsitemanimation.h \
		../../../src/gui/graphicsview/qgraphicsitemanimation.h \
		../../../include/QtGui/qcheckbox.h \
		../../../src/gui/widgets/qcheckbox.h \
		../../../include/QtGui/qabstractbutton.h \
		../../../src/gui/widgets/qabstractbutton.h \
		../../../include/QtGui/qmenu.h \
		../../../src/gui/widgets/qmenu.h \
		../../../include/QtGui/qworkspace.h \
		../../../src/gui/widgets/qworkspace.h \
		../../../include/QtGui/qbuttongroup.h \
		../../../src/gui/widgets/qbuttongroup.h \
		../../../include/QtGui/qspinbox.h \
		../../../src/gui/widgets/qspinbox.h \
		../../../include/QtGui/qlcdnumber.h \
		../../../src/gui/widgets/qlcdnumber.h \
		../../../include/QtGui/qstackedwidget.h \
		../../../src/gui/widgets/qstackedwidget.h \
		../../../include/QtGui/qmdiarea.h \
		../../../src/gui/widgets/qmdiarea.h \
		../../../include/QtGui/qpushbutton.h \
		../../../src/gui/widgets/qpushbutton.h \
		../../../include/QtGui/qmdisubwindow.h \
		../../../src/gui/widgets/qmdisubwindow.h \
		../../../include/QtGui/qsplashscreen.h \
		../../../src/gui/widgets/qsplashscreen.h \
		../../../include/QtGui/qdatetimeedit.h \
		../../../src/gui/widgets/qdatetimeedit.h \
		../../../include/QtGui/qlabel.h \
		../../../src/gui/widgets/qlabel.h \
		../../../include/QtGui/qdockwidget.h \
		../../../src/gui/widgets/qdockwidget.h \
		../../../include/QtGui/qgroupbox.h \
		../../../src/gui/widgets/qgroupbox.h \
		../../../include/QtGui/qdialogbuttonbox.h \
		../../../src/gui/widgets/qdialogbuttonbox.h \
		../../../include/QtGui/qmainwindow.h \
		../../../src/gui/widgets/qmainwindow.h \
		../../../include/QtGui/qtextedit.h \
		../../../src/gui/widgets/qtextedit.h \
		../../../include/QtGui/qprogressbar.h \
		../../../src/gui/widgets/qprogressbar.h \
		../../../include/QtGui/qscrollbar.h \
		../../../src/gui/widgets/qscrollbar.h \
		../../../include/QtGui/qsizegrip.h \
		../../../src/gui/widgets/qsizegrip.h \
		../../../include/QtGui/qtextbrowser.h \
		../../../src/gui/widgets/qtextbrowser.h \
		../../../include/QtGui/qstatusbar.h \
		../../../src/gui/widgets/qstatusbar.h \
		../../../include/QtGui/qtoolbutton.h \
		../../../src/gui/widgets/qtoolbutton.h \
		../../../include/QtGui/qcombobox.h \
		../../../src/gui/widgets/qcombobox.h \
		../../../include/QtGui/qmenudata.h \
		../../../src/gui/widgets/qmenudata.h \
		../../../include/QtGui/qcalendarwidget.h \
		../../../src/gui/widgets/qcalendarwidget.h \
		../../../include/QtGui/qradiobutton.h \
		../../../src/gui/widgets/qradiobutton.h \
		../../../include/QtGui/qmenubar.h \
		../../../src/gui/widgets/qmenubar.h \
		../../../include/QtGui/qfocusframe.h \
		../../../src/gui/widgets/qfocusframe.h \
		../../../include/QtGui/qfontcombobox.h \
		../../../src/gui/widgets/qfontcombobox.h \
		../../../include/QtGui/qtoolbar.h \
		../../../src/gui/widgets/qtoolbar.h \
		../../../include/QtGui/qtoolbox.h \
		../../../src/gui/widgets/qtoolbox.h \
		../../../include/QtGui/qsplitter.h \
		../../../src/gui/widgets/qsplitter.h \
		../../../include/QtGui/qdial.h \
		../../../src/gui/widgets/qdial.h \
		../../../include/QtNetwork/QTcpServer \
		../../../include/QtNetwork/qtcpserver.h \
		../../../src/network/qtcpserver.h \
		../../../include/QtNetwork/qabstractsocket.h \
		../../../src/network/qabstractsocket.h \
		../../../include/QtNetwork/qhostaddress.h \
		../../../src/network/qhostaddress.h \
		../../../include/QtNetwork/QTcpSocket \
		../../../include/QtNetwork/qtcpsocket.h \
		../../../src/network/qtcpsocket.h \
		../../../include/QtNetwork/QHostAddress \
		board.h \
		../../../include/QtGui/QWidget \
		../../../include/QtGui/QImage \
		../../../include/QtGui/QPixmap \
		mainwindow.h \
		../../../include/QtGui/QMainWindow \
		settings.h \
		.uic/release-shared/ui_settings.h \
		../../../include/QtCore/QVariant \
		../../../include/QtGui/QAction \
		../../../include/QtGui/QApplication \
		../../../include/QtGui/QButtonGroup \
		../../../include/QtGui/QCheckBox \
		../../../include/QtGui/QDialog \
		../../../include/QtGui/QGroupBox \
		../../../include/QtGui/QHBoxLayout \
		../../../include/QtGui/QLabel \
		../../../include/QtGui/QLineEdit \
		../../../include/QtGui/QPushButton \
		../../../include/QtGui/QRadioButton \
		../../../include/QtGui/QSpacerItem \
		../../../include/QtGui/QSpinBox \
		../../../include/QtGui/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/mainwindow.o mainwindow.cpp

.obj/release-shared/player.o: player.cpp player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/player.o player.cpp

.obj/release-shared/settings.o: settings.cpp settings.h \
		.uic/release-shared/ui_settings.h \
		../../../include/QtCore/QVariant \
		../../../include/QtCore/qvariant.h \
		../../../src/corelib/kernel/qvariant.h \
		../../../include/QtCore/qatomic.h \
		../../../src/corelib/thread/qatomic.h \
		../../../include/QtCore/qatomic_generic.h \
		../../../src/corelib/arch/qatomic_generic.h \
		../../../include/QtCore/qglobal.h \
		../../../src/corelib/global/qglobal.h \
		../../../include/QtCore/qconfig.h \
		../../../include/QtCore/qfeatures.h \
		../../../src/corelib/global/qfeatures.h \
		../../../include/QtCore/qatomic_arch.h \
		../../../src/corelib/arch/qatomic_arch.h \
		../../../include/QtCore/qatomic_alpha.h \
		../../../src/corelib/arch/qatomic_alpha.h \
		../../../include/QtCore/qatomic_arm.h \
		../../../src/corelib/arch/qatomic_arm.h \
		../../../include/QtCore/qatomic_boundschecker.h \
		../../../src/corelib/arch/qatomic_boundschecker.h \
		../../../include/QtCore/qatomic_i386.h \
		../../../src/corelib/arch/qatomic_i386.h \
		../../../include/QtCore/qatomic_ia64.h \
		../../../src/corelib/arch/qatomic_ia64.h \
		../../../include/QtCore/qatomic_mips.h \
		../../../src/corelib/arch/qatomic_mips.h \
		../../../include/QtCore/qatomic_parisc.h \
		../../../src/corelib/arch/qatomic_parisc.h \
		../../../include/QtCore/qatomic_powerpc.h \
		../../../src/corelib/arch/qatomic_powerpc.h \
		../../../include/QtCore/qatomic_s390.h \
		../../../src/corelib/arch/qatomic_s390.h \
		../../../include/QtCore/qatomic_sparc.h \
		../../../src/corelib/arch/qatomic_sparc.h \
		../../../include/QtCore/qatomic_x86_64.h \
		../../../src/corelib/arch/qatomic_x86_64.h \
		../../../include/QtCore/qbytearray.h \
		../../../src/corelib/tools/qbytearray.h \
		../../../include/QtCore/qlist.h \
		../../../src/corelib/tools/qlist.h \
		../../../include/QtCore/qiterator.h \
		../../../src/corelib/tools/qiterator.h \
		../../../include/QtCore/qalgorithms.h \
		../../../src/corelib/tools/qalgorithms.h \
		../../../include/QtCore/qmetatype.h \
		../../../src/corelib/kernel/qmetatype.h \
		../../../include/QtCore/qdatastream.h \
		../../../src/corelib/io/qdatastream.h \
		../../../include/QtCore/qiodevice.h \
		../../../src/corelib/io/qiodevice.h \
		../../../include/QtCore/qobject.h \
		../../../src/corelib/kernel/qobject.h \
		../../../include/QtCore/qobjectdefs.h \
		../../../src/corelib/kernel/qobjectdefs.h \
		../../../include/QtCore/qnamespace.h \
		../../../src/corelib/global/qnamespace.h \
		../../../include/QtCore/qstring.h \
		../../../src/corelib/tools/qstring.h \
		../../../include/QtCore/qchar.h \
		../../../src/corelib/tools/qchar.h \
		../../../include/Qt3Support/q3cstring.h \
		../../../src/qt3support/tools/q3cstring.h \
		../../../include/QtCore/qcoreevent.h \
		../../../src/corelib/kernel/qcoreevent.h \
		../../../include/QtCore/qmap.h \
		../../../src/corelib/tools/qmap.h \
		../../../include/QtGui/QAction \
		../../../include/QtGui/qaction.h \
		../../../src/gui/kernel/qaction.h \
		../../../include/QtGui/qkeysequence.h \
		../../../src/gui/kernel/qkeysequence.h \
		../../../include/QtGui/qwidget.h \
		../../../src/gui/kernel/qwidget.h \
		../../../include/QtGui/qwindowdefs.h \
		../../../src/gui/kernel/qwindowdefs.h \
		../../../include/QtGui/qpaintdevice.h \
		../../../src/gui/painting/qpaintdevice.h \
		../../../include/QtCore/qrect.h \
		../../../src/corelib/tools/qrect.h \
		../../../include/QtCore/qsize.h \
		../../../src/corelib/tools/qsize.h \
		../../../include/QtCore/qpoint.h \
		../../../src/corelib/tools/qpoint.h \
		../../../include/QtGui/qpalette.h \
		../../../src/gui/kernel/qpalette.h \
		../../../include/QtGui/qcolor.h \
		../../../src/gui/painting/qcolor.h \
		../../../include/QtGui/qrgb.h \
		../../../src/gui/painting/qrgb.h \
		../../../include/QtCore/qstringlist.h \
		../../../src/corelib/tools/qstringlist.h \
		../../../include/QtCore/qregexp.h \
		../../../src/corelib/tools/qregexp.h \
		../../../include/QtCore/qstringmatcher.h \
		../../../src/corelib/tools/qstringmatcher.h \
		../../../include/Qt3Support/q3valuelist.h \
		../../../src/qt3support/tools/q3valuelist.h \
		../../../include/QtCore/qlinkedlist.h \
		../../../src/corelib/tools/qlinkedlist.h \
		../../../include/QtGui/qbrush.h \
		../../../src/gui/painting/qbrush.h \
		../../../include/QtCore/qpair.h \
		../../../src/corelib/tools/qpair.h \
		../../../include/QtCore/qvector.h \
		../../../src/corelib/tools/qvector.h \
		../../../include/QtCore/QPointF \
		../../../include/QtCore/QPoint \
		../../../include/QtGui/qmatrix.h \
		../../../src/gui/painting/qmatrix.h \
		../../../include/QtGui/qpolygon.h \
		../../../src/gui/painting/qpolygon.h \
		../../../include/QtGui/qregion.h \
		../../../src/gui/painting/qregion.h \
		../../../include/QtCore/qline.h \
		../../../src/corelib/tools/qline.h \
		../../../include/QtGui/qwmatrix.h \
		../../../src/gui/painting/qwmatrix.h \
		../../../include/QtGui/qtransform.h \
		../../../src/gui/painting/qtransform.h \
		../../../include/QtGui/qpainterpath.h \
		../../../src/gui/painting/qpainterpath.h \
		../../../include/QtGui/qimage.h \
		../../../src/gui/image/qimage.h \
		../../../include/QtGui/qpixmap.h \
		../../../src/gui/image/qpixmap.h \
		../../../include/QtGui/qfont.h \
		../../../src/gui/text/qfont.h \
		../../../include/QtGui/qfontmetrics.h \
		../../../src/gui/text/qfontmetrics.h \
		../../../include/QtGui/qfontinfo.h \
		../../../src/gui/text/qfontinfo.h \
		../../../include/QtGui/qsizepolicy.h \
		../../../src/gui/kernel/qsizepolicy.h \
		../../../include/QtGui/qcursor.h \
		../../../src/gui/kernel/qcursor.h \
		../../../include/QtGui/qevent.h \
		../../../src/gui/kernel/qevent.h \
		../../../include/QtGui/qmime.h \
		../../../src/gui/kernel/qmime.h \
		../../../include/QtCore/qmimedata.h \
		../../../src/corelib/kernel/qmimedata.h \
		../../../include/QtGui/qdrag.h \
		../../../src/gui/kernel/qdrag.h \
		../../../include/QtGui/qicon.h \
		../../../src/gui/image/qicon.h \
		../../../include/QtGui/qactiongroup.h \
		../../../src/gui/kernel/qactiongroup.h \
		../../../include/QtGui/QApplication \
		../../../include/QtGui/qapplication.h \
		../../../src/gui/kernel/qapplication.h \
		../../../include/QtCore/qcoreapplication.h \
		../../../src/corelib/kernel/qcoreapplication.h \
		../../../include/QtCore/qeventloop.h \
		../../../src/corelib/kernel/qeventloop.h \
		../../../include/QtGui/qdesktopwidget.h \
		../../../src/gui/kernel/qdesktopwidget.h \
		../../../include/QtGui/QButtonGroup \
		../../../include/QtGui/qbuttongroup.h \
		../../../src/gui/widgets/qbuttongroup.h \
		../../../include/QtGui/QCheckBox \
		../../../include/QtGui/qcheckbox.h \
		../../../src/gui/widgets/qcheckbox.h \
		../../../include/QtGui/qabstractbutton.h \
		../../../src/gui/widgets/qabstractbutton.h \
		../../../include/QtGui/QDialog \
		../../../include/QtGui/qdialog.h \
		../../../src/gui/dialogs/qdialog.h \
		../../../include/QtGui/QGroupBox \
		../../../include/QtGui/qgroupbox.h \
		../../../src/gui/widgets/qgroupbox.h \
		../../../include/QtGui/qframe.h \
		../../../src/gui/widgets/qframe.h \
		../../../include/QtGui/QHBoxLayout \
		../../../include/QtGui/qboxlayout.h \
		../../../src/gui/kernel/qboxlayout.h \
		../../../include/QtGui/qlayout.h \
		../../../src/gui/kernel/qlayout.h \
		../../../include/QtGui/qlayoutitem.h \
		../../../src/gui/kernel/qlayoutitem.h \
		../../../include/QtGui/qgridlayout.h \
		../../../src/gui/kernel/qgridlayout.h \
		../../../include/QtGui/QLabel \
		../../../include/QtGui/qlabel.h \
		../../../src/gui/widgets/qlabel.h \
		../../../include/QtGui/QLineEdit \
		../../../include/QtGui/qlineedit.h \
		../../../src/gui/widgets/qlineedit.h \
		../../../include/QtGui/QPushButton \
		../../../include/QtGui/qpushbutton.h \
		../../../src/gui/widgets/qpushbutton.h \
		../../../include/QtGui/QRadioButton \
		../../../include/QtGui/qradiobutton.h \
		../../../src/gui/widgets/qradiobutton.h \
		../../../include/QtGui/QSpacerItem \
		../../../include/QtGui/QSpinBox \
		../../../include/QtGui/qspinbox.h \
		../../../src/gui/widgets/qspinbox.h \
		../../../include/QtGui/qabstractspinbox.h \
		../../../src/gui/widgets/qabstractspinbox.h \
		../../../include/QtGui/qvalidator.h \
		../../../src/gui/widgets/qvalidator.h \
		../../../include/QtCore/qlocale.h \
		../../../src/corelib/tools/qlocale.h \
		../../../include/QtGui/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/settings.o settings.cpp

.obj/release-shared/moc_board.o: .moc/release-shared/moc_board.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_board.o .moc/release-shared/moc_board.cpp

.obj/release-shared/moc_mainwindow.o: .moc/release-shared/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_mainwindow.o .moc/release-shared/moc_mainwindow.cpp

.obj/release-shared/moc_settings.o: .moc/release-shared/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/moc_settings.o .moc/release-shared/moc_settings.cpp

.obj/release-shared/qrc_tavli.o: .rcc/release-shared/qrc_tavli.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/release-shared/qrc_tavli.o .rcc/release-shared/qrc_tavli.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

