######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 3 23:17:03 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CNeuralNet.h types.h
SOURCES += bench.cpp CNeuralNet.cpp nn.cpp
